spring:
  datasource:
    url: jdbc:postgresql://dpg-ceg63tp4reb3r0r74jtg-a.oregon-postgres.render.com/finance_dashboard
    username: root
    password: z9PRSJ0AnHu7KRomStPtWLfrOBbpjbJx

external:
  api:
    url: https://stock-india.onrender.com
