spring:
  datasource:
    url: jdbc:postgresql://bl9rc9tgvuw43h28le6m-postgresql.services.clever-cloud.com/bl9rc9tgvuw43h28le6m
    username: usaauye1xg1qizdcuvla
    password: lRvRSB2mGcjD4bHF0tTj9VkDMyNPJh
    port: 50013
#    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect