spring:
  datasource:
    url: jdbc:postgresql://dpg-cir5hp5iuie930kdop1g-a.oregon-postgres.render.com/finance_dashboard_nzm2
    username: finance_dashboard_nzm2_user
    password: FW098D9PurHDzYrGoeoFimoTn0wWUlHw
