spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance_dashboard
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
external:
  api:
    url: https://stock-india.onrender.com
